### ISSUE TITLE
Flash example does not work on mac

### ISSUE THREAD

**Issue by lebornjose** [hokein/electron-sample-apps#36]
Falsh does not work  PepperFlashPlayer version is  23.0.0.205

**Comment by hokein** [comment]
PepperFlashPlayer v23.0.0.205 is used in Chrome 54, but the latest Electron v1.4.4 is still based on Chrome 53, so you need to use the version of PepperFlashPlayer which is corresponding to Chrome 53.0.2785.113 (I don't the exact version for it because my chrome is 54 already). 

Maybe I should clarify the readme document of the pepper sample. The current words `Copy from Chrome Browser` are a bit of misleading.

**Comment by lebornjose** [comment]
I should go see download the correct PepperFlashPlayer?

**Comment by hokein** [comment]
Yeah, exactly. I found that chrome 53 is using 23.0.0.162.
